model_list:
  - model_name: gemini-3-flash-preview
    litellm_params:
      model: vertex_ai/gemini-3-flash-preview
      api_base: https://aiplatform.googleapis.com
      api_key: os.environ/GEMINI_API_KEY
      rpm: 6
  - model_name: kimi-k2-thinking-maas
    litellm_params:
      model: openai/moonshotai/kimi-k2-thinking-maas
      api_base: https://us-central1-aiplatform.googleapis.com/v1/projects/PROJECT_ID/locations/us-central1/endpoints/openapi
      api_key: os.environ/KIMI_ACCESS_TOKEN
router_settings:
  redis_host: os.environ/REDIS_HOST
  redis_port: os.environ/REDIS_PORT
  redis_password: os.environ/REDIS_PASSWORD
